#!/usr/bin/env python3
"""Chinese UI strings for the sc-offline mod menu and status line (sc-offline 0.7.0).

The record of every translated menu string: applied to a copy of the upstream English src/, it
gives the literal swaps of the zh-cn branch (the ship/place-name and font code is not in here).
Every entry is an exact C string literal (without quotes) in one file. MinGW's printf has no
positional arguments (%2$s), so where Chinese wants another order the call's arguments are
swapped instead (see SHOWN).
usage: sc-offline-zh-strings.py <upstream-src-dir>
"""
import sys, os

T = {
'menu.cpp': [
    ("Loading NPCs (you need to be in the universe)...", "正在加载 NPC（需要先进入游戏世界）..."),
    ("No NPCs found. Check data\\\\npcs.txt.", "没有找到 NPC，请检查 data\\\\npcs.txt。"),
    ("Search NPCs", "搜索 NPC"),
    ("Movement", "移动"),
    ("Noclip", "穿墙飞行"),
    ("Speed %.0f", "速度 %.0f"),
    ("F7 saves where you're standing and F8 takes you back. The Travel tab has named spots and places.",
     "F7 记录当前位置，F8 传送回去。“传送”标签页里还有命名地点和各类目的地。"),
    ("Protection", "保护"),
    ("God mode", "无敌模式"),
    ("Infinite ammo", "无限弹药"),
    ("Gear", "装备"),
    ("Undersuit", "内衬服"), ("Default", "默认"), ("Helmet", "头盔"), ("None", "无"), ("Body", "躯干护甲"),
    ("Arms", "手臂护甲"), ("Legs", "腿部护甲"), ("Backpack", "背包"), ("Primary", "主武器"), ("Sidearm", "副武器"),
    ("Ammo", "弹药"), ("Matches weapon", "与武器匹配"), ("Grenades", "手雷"),
    ("Loading gear (you need to be in the universe)...", "正在加载装备（需要先进入游戏世界）..."),
    ("Search gear", "搜索装备"),
    ("Equip gear", "穿戴装备"),
    ("Search places and saved spots", "搜索地点和已保存的位置"),
    ("Places", "地点"),
    ("Arrive %.0f m above the ground", "到达时离地 %.0f 米"),
    ("Show interiors and small zones", "显示室内和小区域"),
    ("Elevator lobbies, hangars, asteroid-belt segments and similar. Hidden by default.",
     "电梯大厅、机库、小行星带分段等，默认隐藏。"),
    ("Unnamed system", "未命名星系"),
    (", you are here", "，你在这里"),
    ("Place", "地点"),
    ("Type", "类型"),
    ("Planet", "行星"), ("Moon", "卫星"), ("Interior", "室内"),
    (", orbit", "，轨道"),
    ("Go to %s", "前往 %s"),
    ("Pick a place to go", "选择一个目的地"),
    ("Scanning...", "正在扫描..."),
    ("Scan the game for places", "扫描游戏中的地点"),
    ("The scan finds the planets, moons, stations, Lagrange points, comm arrays and jump points of every loaded ",
     "扫描会找出所有已加载星系中的行星、卫星、空间站、拉格朗日点、通讯阵列和跳跃点，"),
    ("system and adds them here. It only reads; it takes a few seconds.", "并添加到这里。只读取不修改，需要几秒钟。"),
    ("Saved spots", "已保存的位置"),
    ("Name this spot", "给这个位置起个名字"),
    ("Save this spot", "保存当前位置"),
    ("Nothing saved yet. Stand somewhere, name it, and press Save this spot.",
     "还没有保存任何位置。站到想去的地方，起个名字，再点“保存当前位置”。"),
    ("Go", "前往"),
    ("Delete", "删除"),
    ("F7 and F8 still work as a quick save slot. Teleports only work within the system you're in.",
     "F7/F8 仍可作为快速存档位使用。传送只能在你当前所在的星系内进行。"),
    ("Spawn a ship", "生成飞船"),
    ("Loading ships (you need to be in the universe)...", "正在加载飞船列表（需要先进入游戏世界）..."),
    ("No ships found. Check data\\\\ships.txt.", "没有找到飞船，请检查 data\\\\ships.txt。"),
    ("Search ships", "搜索飞船（中文名或代号）"),
    ("Ship", "飞船"),
    ("Size", "尺寸"),
    ("Length", "长度"),
    ("Spawn %.0f m above you", "在你上方 %.0f 米处生成"),
    ("Don't board", "不登船"),
    ("Board in the pilot seat", "登船并坐上驾驶座"),
    ("Board in a seat by name", "按名称选择座位登船"),
    ("Choose a seat after it spawns", "生成后再选座位"),
    ("Seat name, e.g. copilot or turret left", "座位名称，例如 copilot 或 turret left"),
    ("Every word must appear in the seat's name. The Crew tab shows a ship's seat names.",
     "每个词都必须出现在座位名称里。“船员”标签页可以查看飞船的座位名称。"),
    ("Remove the NPC in my seat", "移除我座位上的 NPC"),
    ("Power on", "启动电源"),
    ("Powers the ship on once you're in a pilot seat.", "坐上驾驶座后自动启动飞船电源。"),
    ("Current ship", "当前飞船"),
    ("Infinite ship ammo", "飞船无限弹药"),
    ("Refills the magazines of the ship you're aboard, and the ship in the Crew tab.",
     "为你所在的飞船以及“船员”标签页中选中的飞船补满弹药。"),
    ("Power on / off", "电源开 / 关"),
    ("Toggles Flight Ready on the ship in the Crew tab, as if you pressed R in its pilot seat.",
     "切换“船员”标签页中飞船的飞行就绪状态，相当于在驾驶座按 R。"),
    ("Crew", "船员"),
    ("Seat control isn't available in this game version. mod.log has the details.",
     "当前游戏版本不支持座位控制，详情见 mod.log。"),
    ("No ship selected", "未选择飞船"),
    ("Use the ship I'm in", "使用我所在的飞船"),
    ("Spawn a ship, or board one and press 'Use the ship I'm in'.", "先生成一艘飞船，或登上一艘后点“使用我所在的飞船”。"),
    ("Waiting for the ship to load...", "正在等待飞船加载..."),
    ("Seats", "座位"),
    ("Seat", "座位"),
    ("Occupant", "乘员"),
    ("You", "你"), ("Unknown", "未知"), ("Empty", "空"),
    ("Sit here", "坐这里"),
    ("Stand up", "起身"),
    ("Whoever is in the seat gets up and stays aboard.", "让座位上的人起身，但留在船上。"),
    ("Remove NPC", "移除 NPC"),
    ("Takes the NPC out of the game.", "把这个 NPC 从游戏中移除。"),
    ("Add NPC", "添加 NPC"),
    ("If an NPC is in the seat I pick, remove it", "如果选中的座位上有 NPC，先移除它"),
    ("NPC to add to seats:", "要安排到座位上的 NPC："),
    ("Fill empty seats", "填满空座位"),
    ("All NPCs stand up", "所有 NPC 起身"),
    ("Remove all NPCs", "移除所有 NPC"),
    ("NPCs you add sit in their seats. They don't fly the ship or operate turrets yet.",
     "添加的 NPC 只会坐在座位上，暂时不会驾驶飞船或操作炮塔。"),
    ("Spawn NPCs", "生成 NPC"),
    ("1 NPC", "1 个 NPC"), ("%d NPCs", "%d 个 NPC"),
    ("Spawn in front of me", "在我面前生成"),
    ("Remove spawned NPCs", "移除已生成的 NPC"),
    ("Removes every NPC this menu has spawned, crew included.", "移除这个菜单生成的所有 NPC，包括船员。"),
    ("Objects", "物体"),
    ("Loading build objects (you need to be in the universe)...", "正在加载建造物体（需要先进入游戏世界）..."),
    ("No build objects found. Check data\\\\buildables.txt.", "没有找到建造物体，请检查 data\\\\buildables.txt。"),
    ("Search all objects", "搜索所有物体"),
    ("Placing", "放置"),
    ("Selected: %s", "已选择：%s"),
    ("Reach %.0f m", "放置距离 %.0f 米"),
    ("How far ahead objects are placed. They land on the ground where you look, or under the point this far out.",
     "物体放在前方多远处：落在你视线所指的地面上，或这个距离处正下方的地面上。"),
    ("Stop building (F6)", "停止建造（F6）"),
    ("Start building (F6)", "开始建造（F6）"),
    ("Undo last", "撤销上一步"),
    ("Clear base (%d)###clearBase", "清空基地（%d）###clearBase"),
    ("While building: left click places, R rotates, [ and ] change reach, Backspace undoes, F6 stops.",
     "建造时：左键放置，R 旋转，[ 和 ] 调整距离，Backspace 撤销，F6 停止。"),
    ("Background", "背景"),
    ("Show background image", "显示背景图片"),
    ("Darkness %d%%", "暗度 %d%%"),
    ("Image position", "图片位置"),
    ("The menu is taller than the picture is wide. Slide to choose which part shows.", "菜单比图片宽度更高，拖动滑块选择显示图片的哪一部分。"),
    ("To use a background image, save it as menu_background.png (or .jpg) here, then restart the game:",
     "要使用背景图片，请把它保存为下面位置的 menu_background.png（或 .jpg），然后重启游戏："),
    ("About", "关于"),
    ("Spoiler warning", "剧透警告"),
    ("This tab could have Squadron 42 spoilers.", "这个标签页可能含有《42 中队》的剧透。"),
    ("Press OK to continue.", "点“确定”继续。"), ("OK", "确定"), ("Back", "返回"),
    ("Outfits", "服装"),
    ("Loading outfits... (you need to be spawned in the universe)", "正在加载服装...（需要先进入游戏世界）"),
    ("No outfits found - check outfits.txt.", "没有找到服装，请检查 outfits.txt。"),
    ("search outfits...", "搜索服装..."),
    ("SQ42 visor HUD (applies on the next Equip or outfit)", "SQ42 面罩 HUD（下次穿戴装备或服装时生效）"),
    ("Wear SQ42 outfit", "穿上 SQ42 服装"),
    ("Settings", "设置"),
    ("Spawn", "生成"),
    ("Loading... (you need to be spawned in the universe)", "正在加载...（需要先进入游戏世界）"),
    ("No buildables found - check buildables.txt.", "没有找到可建造物体，请检查 buildables.txt。"),
    ("Spawn in front of you", "在你面前生成"),
    ("search the [sq42] group...", "搜索 [sq42] 分组..."),
    ("ahead (m)", "前方距离（米）"),
    ("Spawn it", "生成它"),
    ("Undo and Clear base in the build section remove these too.", "建造部分的“撤销”和“清空基地”也会移除这些物体。"),
    ("Ships", "飞船"),
    ("Idris-P (the Stanton's class)", "伊德里斯-P（斯坦顿号同级舰）"),
    ("Gladius (SQ42 fighter)", "角斗士（SQ42 战斗机）"),
    ("Retaliator (has an S42 HUD)", "报复者（带 S42 HUD）"),
    ("Starfarer (ch 5, 7, 9)", "星际远航者（第 5、7、9 章）"),
    ("Avenger Stalker (S42 wreck)", "复仇者潜行者（S42 残骸）"),
    ("Hornet (Cal Mason's ship)", "大黄蜂（卡尔·梅森的座驾）"),
    ("Vanduul Blade (AI)", "范杜尔刀锋（AI）"),
    ("Vanduul Scythe (AI)", "范杜尔镰刀（AI）"),
    ("Vanduul Glaive (AI)", "范杜尔长柄刀（AI）"),
    ("Vanduul Stinger (AI)", "范杜尔毒刺（AI）"),
    ("Bengal + Vanduul wing", "孟加拉 + 范杜尔编队"),
    ("Bengal + wing (UEE, no enemy side found)", "孟加拉 + 编队（UEE，未找到敌方阵营）"),
    ("Bengal (UEE)", "孟加拉（UEE）"),
    ("%s isn't in this game build's ship list.", "当前游戏版本的飞船列表里没有 %s。"),
    ("Reading this setting from the game...", "正在从游戏读取此设置..."),
    ("Your ships put you in the pilot seat; the Vanduul ones spawn 300 m up and come for you.",
     "己方飞船会让你坐上驾驶座；范杜尔飞船在上方 300 米生成并向你发起攻击。"),
    ("search ships...", "搜索飞船..."),
    ("height above me (m)", "离我的高度（米）"),
    ("put me in the pilot seat", "让我坐上驾驶座"),
    ("Console", "控制台"),
    ("a console command, e.g. i_target_selector.targeting2_enabled 1", "控制台命令，例如 i_target_selector.targeting2_enabled 1"),
    ("Run", "执行"), ("The game's console wasn't found yet.", "还没有找到游戏的控制台。"),
    ("Runs in the game's own console. What it did shows in the game's log, not here.", "在游戏自带的控制台中执行，结果写在游戏日志里，不在这里显示。"),
    ("Player", "玩家"), ("Travel", "传送"), ("Vehicles", "载具"), ("NPCs", "NPC"), ("Build", "建造"),
    ("Squadron 42", "42 中队"), ("Menu", "菜单"),
],
'spawner.cpp': [
    ("Pick a ship and press Spawn.", "选择一艘飞船，然后点“生成”。"),
    ("%s powered on - sent the game's Flight Ready event to the pilot dashboard.", "%s 已通电，已向驾驶舱仪表板发送飞行就绪事件。"),
    ("Couldn't reach the %s's dashboard directly - pressed Flight Ready (R) for you.", "无法直接访问 %s 的仪表板，已替你按下飞行就绪（R）。"),
    ("Couldn't reach the %s's dashboard. Press R (Flight Ready) to power up.", "无法访问 %s 的仪表板，请按 R（飞行就绪）启动。"),
    ("You're in the %s's pilot seat - powering up...", "你已坐上 %s 的驾驶座，正在启动..."),
    ("You're in the %s's pilot seat ('%s'). Press R (Flight Ready) to power up.", "你已坐上 %s 的驾驶座（“%s”）。按 R（飞行就绪）启动。"),
    ("You're in the %s, but its pilot seat wasn't free%s - you got '%s'.", "你已登上 %s，但驾驶座被占用%s，你坐在“%s”。"),
    ("You're in '%s' on the %s.", "你坐在“%s”（%s）。"),
    ("You're in the %s. Have fun!", "你已登上 %s，玩得开心！"),
    ("%s spawned, but I couldn't get you aboard within 3 minutes.", "%s 已生成，但 3 分钟内没能让你登船。"),
    ("That seat isn't on the %s any more - refresh the list.", "%s 上已经没有这个座位了，请刷新列表。"),
    ("The NPC in '%s' keeps coming back - try another seat.", "“%s”上的 NPC 一直回来，请换个座位。"),
    ("'%s' has an NPC in it - tick 'replace NPC' or kick it first.", "“%s”上有 NPC，请勾选“移除我座位上的 NPC”或先把它请走。"),
    ("'%s' is taken by someone I can't identify, so I left it.", "“%s”被无法识别的人占用，所以没有动它。"),
    ("Removing the NPC from '%s' on the %s...", "正在移除“%s”上的 NPC（%s）..."),
    ("Seating failed (fault).", "入座失败（出错）。"),
    ("Asked %s to seat you 8 times; it didn't take.", "已请求 %s 让你入座 8 次，均未成功。"),
    ("Can't pick your ship: %s", "无法选中你的飞船：%s"),
    ("Crew & seats now shows the %s.", "“船员”页现在显示 %s。"),
    ("Seat control isn't available in this game version.", "当前游戏版本不支持座位控制。"),
    ("Spawn a ship first (or press 'Use the ship I'm in').", "请先生成一艘飞船（或点“使用我所在的飞船”）。"),
    ("The %s isn't loaded (or has no seats).", "%s 还没加载完（或者没有座位），请稍等几秒再试。"),
    ("That seat is gone - refresh the list.", "这个座位已经不存在，请刷新列表。"),
    ("Moving you to '%s'...", "正在把你移到“%s”..."),
    ("Removed the NPC from '%s'.", "已移除“%s”上的 NPC。"),
    ("Can't tell who is in '%s', so I left them.", "无法确定“%s”上是谁，所以没有动。"),
    ("There's no NPC in '%s'.", "“%s”上没有 NPC。"),
    ("You got out of '%s'.", "你已离开“%s”。"),
    ("Couldn't get you out of '%s'.", "无法让你离开“%s”。"),
    ("The NPC in '%s' stood up.", "“%s”上的 NPC 已起身。"),
    ("Couldn't get the NPC out of '%s'.", "无法让“%s”上的 NPC 离开。"),
    ("'%s' is already empty.", "“%s”已经是空的。"),
    ("%d of %d NPCs on the %s stood up.", "已有 %d / %d 个 NPC 起身（%s）。"),
    ("'%s' isn't empty - kick its occupant first.", "“%s”不是空的，请先让上面的人离开。"),
    ("Adding crew failed: %s", "添加船员失败：%s"),
    ("Seating %s in '%s'...", "正在把 %s 安排到“%s”..."),
    ("Filling seats failed: %s", "填充座位失败：%s"),
    ("Seating %d x %s on the %s...", "正在安排 %d 个 %s 入座（%s）..."),
    ("Removed %d NPC crew from the %s.", "已移除 %d 名 NPC 船员（%s）。"),
    ("Flight Ready event not available - press R in the pilot seat.", "无法发送飞行就绪事件，请在驾驶座按 R。"),
    ("Going to Daymar failed: %s", "前往戴玛失败：%s"),
    ("Spawning %s %.0f km over Daymar - you'll be put in its pilot seat, then fly down and land.",
     "正在生成 %s（戴玛上空 %.0f 公里），你会被安排到驾驶座，然后飞下去降落。"),
    ("Noclip isn't available (fly mode not found).", "穿墙飞行不可用（未找到飞行模式）。"),
    ("Noclip %s failed: %s", "穿墙飞行%s失败：%s"),
    ("Noclip %s (speed %.0f).", "穿墙飞行%s（速度 %.0f）。"),
    ("Spawning %s failed: %s", "生成 %s 失败：%s"),
    (" (tick 'replace NPC' to take it)", "（勾选“移除我座位上的 NPC”即可占用）"),
    ("%s spawned %.0f m above you; %d of 3 enemy wing ships came in at 300 m.", "%s 已在你上方 %.0f 米生成；3 艘敌方僚机中有 %d 艘在 300 米处出现。"),
    ("Spawning %s %.0f m above you (big ships take up to a minute).", "正在你上方 %.0f 米处生成 %s（大船最多需要一分钟）。"),
    ("Spawning %s - you'll be put in the pilot seat as soon as it's there (big ships take up to a minute).",
     "正在生成 %s，生成后会立即安排你坐上驾驶座（大船最多需要一分钟）。"),
    ("Spawning %s - pick a seat under Crew & seats once it has loaded.", "正在生成 %s，加载完成后请在“船员”页选择座位。"),
    ("Spawning %s - you'll be put in a '%s' seat as soon as it's there.", "正在生成 %s，生成后会把你安排到“%s”座位。"),
],
'cvars.cpp': [
    ("SQ42 auto targeting", "SQ42 自动瞄准"),
    ('\\"Enables the auto targeting feature for SQ42\\" (the game mode can override it).',
     "“为 SQ42 启用自动瞄准功能”（游戏模式可能会覆盖这个设置）。"),
    ("Visor mini-map", "面罩小地图"), ("The mini-map on your visor HUD.", "面罩 HUD 上的小地图。"),
    ("Visor greebles", "面罩装饰"), ("The decorative frame pieces on your visor HUD.", "面罩 HUD 上的装饰性边框。"),
    ("SQ42 menus (experimental)", "SQ42 菜单（实验功能）"),
],
'travel.cpp': [
    ("A scan is already running.", "扫描已经在进行中。"),
    ("Scanning for places...", "正在扫描地点..."),
    ("Scan finished: %d new place%s.", "扫描完成：新增 %d 个地点%s。"),
    ("Teleported to %s, %.0f m above the surface.", "已传送到 %s，离地 %.0f 米。"),
    ("Teleported to %s. Its size isn't known, so you're in orbit - fly in from here.", "已传送到 %s。不知道它的大小，所以把你放在了轨道上，请从这里飞过去。"),
    ("Teleported to %s.", "已传送到 %s。"),
    ("Can't go to '%s': %s.", "无法前往“%s”：%s。"),
    ("Teleported to '%s'.", "已传送到“%s”。"),
    ("Couldn't save this spot: %s.", "无法保存当前位置：%s。"),
    ("You have %d saved spots; delete one first.", "你已经保存了 %d 个位置，请先删除一个。"),
    ("Saved '%s' (%s).", "已保存“%s”（%s）。"),
    ("Deleted '%s'.", "已删除“%s”。"),
    ("isn't loaded - it may be in another system, or the name in the list is wrong (try the scan)",
     "未加载：它可能在其他星系，或者列表里的名称有误（可以试试扫描）"),
    ("found, but it has no id to teleport to", "已找到，但没有可传送的目标 ID"),
],
}

# Strings that change layout or meaning beyond a literal swap.
EXTRA = [
    ('spawner.cpp', 'static char          g_menuStatus[256]', 'static char          g_menuStatus[768]'),
    ('spawner.cpp', 'void SetMenuStatus(const char* fmt, ...) {\n    char buf[256];', 'void SetMenuStatus(const char* fmt, ...) {\n    char buf[768];'),
    ('menu.cpp', 'static void DrawStatusStrip(float height) {\n    char status[256];', 'static void DrawStatusStrip(float height) {\n    char status[768];'),
    # SCO_BASED_ON is English; the About lines say it in Chinese and add the fork's issue tracker.
    ('menu.cpp', '    Hint(SCO_TITLE " is a work in progress, " SCO_BASED_ON ".");\n    Hint("Bug reports: github.com/scubamount/sc-offline/issues");\n',
     '    // SCO_BASED_ON in Chinese.\n    Hint(SCO_TITLE " 仍在开发中，基于 ChrisWareOffline 0.9.0-rc1。");\n'
     '    Hint("问题反馈：github.com/scubamount/sc-offline/issues");\n    Hint("中文版问题：github.com/dazi2011/sc-offline/issues");\n'),
    # A tip split over two literals.
    ('cvars.cpp', '"\\"Enable Squadron 42 Frontend\\". Switches the pause menu and loading screens to SQ42\'s, whose data is "\n'
                  '      "missing; turn it off before traveling or quitting if anything breaks.",',
     '"“启用《42 中队》前端”。把暂停菜单和加载画面换成 SQ42 的，但相关数据缺失；"\n'
     '      "如果出了问题，请在传送或退出游戏前把它关掉。",'),
    # The plural suffix makes no sense in Chinese.
    ('travel.cpp', 'n, n == 1 ? "" : "s");', 'n, "");'),
    # "Noclip on/off" words.
    ('spawner.cpp', 'req.on ? "on" : "off", err);', 'req.on ? "开启" : "关闭", err);'),
    ('spawner.cpp', 'req.on ? "on" : "off", req.speed);', 'req.on ? "已开启" : "已关闭", req.speed);'),
    # Spawn-from-menu messages show the Chinese name; the class name still drives spawning.
    ('spawner.cpp', '        const char* name = g_menuShips[req.index].name;\n',
     '        const char* name = g_menuShips[req.index].name;\n        const char* shown = g_menuShips[req.index].display[0] ? g_menuShips[req.index].display : name;\n'),
]
# After the literal swap, the menu-spawn branch prints `shown` instead of `name`.
SHOWN = [
    ('SetMenuStatus("生成 %s 失败：%s", name, err);', 'SetMenuStatus("生成 %s 失败：%s", shown, err);'),
    ('SetMenuStatus("正在你上方 %.0f 米处生成 %s（大船最多需要一分钟）。", name, o.height);',
     'SetMenuStatus("正在你上方 %.0f 米处生成 %s（大船最多需要一分钟）。", o.height, shown);'),
    ('SetMenuStatus("正在生成 %s，加载完成后请在“船员”页选择座位。", name);', 'SetMenuStatus("正在生成 %s，加载完成后请在“船员”页选择座位。", shown);'),
    ('SetMenuStatus("正在生成 %s，生成后会把你安排到“%s”座位。", name, o.seatName);', 'SetMenuStatus("正在生成 %s，生成后会把你安排到“%s”座位。", shown, o.seatName);'),
    ('SetMenuStatus("正在生成 %s，生成后会立即安排你坐上驾驶座（大船最多需要一分钟）。", name);', 'SetMenuStatus("正在生成 %s，生成后会立即安排你坐上驾驶座（大船最多需要一分钟）。", shown);'),
    # SQ42 tab spawns pass the class first; the Chinese text puts the height first.
    ('SetMenuStatus("正在你上方 %.0f 米处生成 %s（大船最多需要一分钟）。", classReq.cls, classReq.height);',
     'SetMenuStatus("正在你上方 %.0f 米处生成 %s（大船最多需要一分钟）。", classReq.height, classReq.cls);'),
]

def main(src):
    missing = []
    for f, pairs in T.items():
        p = os.path.join(src, f); s = open(p, encoding='utf-8').read()
        for en, zh in pairs:
            lit = '"' + en + '"'
            if lit not in s: missing.append(f'{f}: literal not found: {en}'); continue
            s = s.replace(lit, '"' + zh + '"')
        open(p, 'w', encoding='utf-8').write(s)
    for f, old, new in EXTRA:
        p = os.path.join(src, f); s = open(p, encoding='utf-8').read()
        if s.count(old) != 1: missing.append(f'{f}: expected one occurrence of: {old[:60]}'); continue
        open(p, 'w', encoding='utf-8').write(s.replace(old, new))
    p = os.path.join(src, 'spawner.cpp'); s = open(p, encoding='utf-8').read()
    for old, new in SHOWN:
        if s.count(old) < 1: missing.append(f'spawner.cpp: not found: {old[:60]}'); continue
        s = s.replace(old, new)
    open(p, 'w', encoding='utf-8').write(s)
    if missing: sys.exit('\n'.join(missing))
    print('SC_OFFLINE_ZH_STRINGS_APPLIED')

main(sys.argv[1])
